### ISSUE TITLE
Image search...

### ISSUE THREAD

**Issue by Flikowski** [devunt/make-gis-great-again#6] opened 2018-02-16 18:36 UTC
Hey

You can still improve it so that after clicking on the thumbnail you can open the picture from the times it was before?

Alternatively, add a button to show the image on this sub-page after clicking the thumbnail.

I mean [THIS](https://www.google.com/search?num=50&newwindow=1&hl=en&tbs=sbi:AMhZZiuw4SSZS-MnfoGW9VGn9ujL9HHt_1vO4gv5h288IYV_1Tt2LrUIGHZwZ4AfVex8905geLbFWVjQZn4RFb_1KQvUXlMKP4Ds6dJqHBuyTvhosRmryjLudjSHQbq-Fb3K5eBn7ssUeapYPEsiOJGmiMJx4L4jO4jd7RbsYel_1JkLBihrFj6qfa2RWWrrOwLxRs9XXYJ7GfBEEzG-6iCauDfr4nP7OktzcMDX6_1BT4Y3thUhImSswHvu3wRgXgvPwDpkz5JIEEpPZV9OC9AIx8ANo6sppCpNqWUlYilRwwAqAauRFzugMG1SJiGQDE52ADhddu9Aw-qqv&ei=qReHWor8Ccv1kwWHr7ngAw&start=10&sa=N&biw=1391&bih=810) and [THIS](https://www.google.com/imgres?imgurl=https://16347-presscdn-0-0-pagely.netdna-ssl.com/wp-content/uploads/2017/01/loki_kitteh2-720x720.png&imgrefurl=https://getleashedmag.com/2017/08/16/this-kitty-is-likely-part-vampire/?ref=news&h=720&w=720&tbnid=a_ETcLz8fQi4dM&tbnh=225&tbnw=225&usg=__BaygH7mO1E6Mm51TEPmagyp1BEI=&hl=en&docid=u_b7lErZcMZ7fM).

Thanks

**Comment by devunt** [comment] 2018-02-17 07:04
Closing as a duplicate of #4.

**Closed by devunt** 2018-02-17 07:04 UTC
