### ISSUE TITLE
Doesn't work when click a related image.

### ISSUE THREAD

**Issue by Almo7aya** [devunt/make-gis-great-again#21] opened 2018-02-18 13:46 UTC
When I click a related image the view-image button doesn't update the new image url,
I've read the source code, I know how it works, I tried to fix it but, I didn't find the new related image JSON data.

**Comment by devunt** [comment] 2018-02-18 19:56
Closing as this is duplicate of #4. Anyway, for your infromation, it was fixed just ago!

**Closed by devunt** 2018-02-18 19:56 UTC
