### ISSUE TITLE
[UserScript] Doesn't work on "shared" results pages

### ISSUE THREAD

**Issue by fixator10** [devunt/make-gis-great-again#11] opened 2018-02-17 06:55 UTC
[Example](https://goo.gl/images/JDQJY5)
![image](https://user-images.githubusercontent.com/11073934/36338768-0bf2a254-13d1-11e8-9abc-0fd9f5b27779.png)

**Comment by devunt** [comment] 2018-02-17 07:05
Closing as a duplicate of #4, #6. Anyway, thanks for reporting!

**Closed by devunt** 2018-02-17 07:05 UTC

**Comment by fixator10** [comment] 2018-02-24 09:16
#4 is closed, but button still doesn't appears on **shared** search pages
![gif](https://Moeka.is-a-good-waifu.com/d94650.gif)

**Comment by AHOHNMYC** [comment] 2018-02-24 11:16
Try [my fork](https://github.com/AHOHNMYC/make-gis-great-again/) as temporary solution. Hope, it'll be [merged](https://github.com/devunt/make-gis-great-again/pull/44) to master soon.

**Comment by fixator10** [comment] 2018-02-24 14:55
@AHOHNMYC now its doesnt work even on standart search

![gif](https://Moeka.is-a-good-waifu.com/5b803a.gif)

**Comment by AHOHNMYC** [comment] 2018-02-24 15:15
@fixator10 please try again. Hope, i've fixed it with last commit.

**Comment by fixator10** [comment] 2018-02-24 15:19
@AHOHNMYC seems fine now, but "Share" button...
![image](https://Moeka.is-a-good-waifu.com/ad4d5b.png)
