### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by arisboch** [devunt/make-gis-great-again#18] opened 2018-02-17 19:26 UTC
Neither the extension nor the Userscript work (anymore?). Did Google Images change the layout of their result page?

**Comment by Aidoboy** [comment] 2018-02-17 20:45
It's still working for me.

**Comment by WERT7** [comment] 2018-02-17 21:20
When I use the button to open full image from 'similar images' list, it opens initial image

**Comment by rachmadaniHaryono** [comment] 2018-02-17 22:50
in my case userscript don't work, but the extension does

**Comment by accorp** [comment] 2018-02-18 00:13
@rachmadaniHaryono
Thanks for the hint. Chrome extension contains [older version](https://github.com/devunt/make-gis-great-again/raw/1ac0a5356def15912f56616aaea10c3f21f6c2da/gis-vib.user.js) which works fine.

**Comment by deuxsonic** [comment] 2018-02-18 04:24
I can confirm it doesn't work with Firefox or Chrome. The button does not appear.

**Comment by arisboch** [comment] 2018-02-18 20:32
Now it works again, what kinda sorcery is that?!

**Comment by devunt** [comment] 2018-02-18 20:36
Have no idea. Anyway since it works by now, I'm closing this issue.

**Closed by devunt** 2018-02-18 20:36 UTC
Labels: weird

**Comment by rachmadaniHaryono** [comment] 2018-02-18 20:37
I think there should be a way to see if script is actually working.

Maybe log something on  Webbrowser console including the program version

So next time user report that the program don't work, they should put the log here
