### ISSUE TITLE
Bring back "Search by image" button

### ISSUE THREAD

**Issue by pushbox** [devunt/make-gis-great-again#19] opened 2018-02-18 10:13 UTC
https://github.com/bijij/ViewImage
This developer's browser extensions for Firefox and Chrome can bring back both buttons. But I really really want to keep using Safari on Mac. Can you update the Userscripts to restore both "View Image" and "Search by image" buttons?
Thank you very much!

**Comment by devunt** [comment] 2018-02-18 20:50
Closing as duplicate of #16

**Closed by devunt** 2018-02-18 20:50 UTC
