### ISSUE TITLE
Install does nothing on Firefox ESR 52.6.0 (32-bit)

### ISSUE THREAD

**Issue by deuxsonic** [devunt/make-gis-great-again#27] opened 2018-02-19 04:49 UTC
Can anyone else confirm if this add-on works with Firefox ESR on their computer? It installs but appears to do nothing.

**Comment by devunt** [comment] 2018-02-19 05:06
Possibly duplicate of #14?

**Comment by deuxsonic** [comment] 2018-02-19 05:16
Yes, I think so.

**Comment by devunt** [comment] 2018-02-19 05:19
Closing as duplicate!

**Closed by devunt** 2018-02-19 05:19 UTC
